# Generated by Django 3.2.12 on 2022-02-03 06:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testuploadapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='MobileModel',
            new_name='person',
        ),
    ]
